apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubble-backend-deployment
  # namespace: team-aqua
  labels:
    app: bubble-backend
spec:
  replicas: 1
  # minReadySeconds: 5
  # strategy: 
  #   type: blue
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: bubble-backend
  template:
    metadata:
      labels:
        app: bubble-backend
    spec:
      containers:
      - name: bubble-backend-container
        image: archieaqua/bubble-b:test
        resources:
          requests:
            memory: "512Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            # cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: bubble-secret
                key: db-url
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: bubble-secret
                key: db-username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: bubble-secret
                key: db-password
          - name: MAIL_ADDR
            valueFrom:
              secretKeyRef:
                name: bubble-secret
                key: email-address
          - name: MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: bubble-secret
                key: email-pass

