apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  # namespace: green
spec:
  selector:
    matchLabels:
      app: bubble
      tier: frontend
      color: green
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bubble
        tier: frontend
        color: green
        track: stable
    spec:
      nodeSelector:
        name: w1
      containers:
        - name: nginx
          image: "archieaqua/bubble-f:test.bg"
          ports:
            - containerPort: 80
